### ISSUE TITLE
underground mapping

### ISSUE THREAD

**Issue by ghost** [GoryMoon/GlobalGameRules#1]
I looked for a forum but couldn't find what I was looking for. Please forgive me if this is the wrong place.

So when I am underground, lets say digging a strait line tunnel. I can see caves and lava/water, but I can not tell what level they are on compared to me. Can you tell me the range, and possibly include a way to configure that range? It sometimes doesnt matter to me unless I am going right into a pool of lava. Other times I really want to get into that cave or mine system without digging several blocks up and down to find it. Maybe if you highlight the area in the mini map it could show the floor level or something?

Thanks.

**Comment by GoryMoon** [comment]
I think you got the wrong github repository, this mod don't have anything with minimaps to do, so I can't help you with that.
