### ISSUE TITLE
[1.19.2 / CRASH] Mod crashing the game on world creation.

### ISSUE THREAD

**Issue by murao-kun** [GoryMoon/GlobalGameRules#12]
[crash-2022-09-30_17.04.33-server.txt](https://github.com/GoryMoon/GlobalGameRules/files/9685047/crash-2022-09-30_17.04.33-server.txt)

**Comment by wendall911** [comment]
I can confirm this crash. It' is with a newer version of Forge after 43.1.27 that is not reading the config files early enough for mods to pick up in the startup process. I'm only seeing this: 43.1.30 Make ForgeConfigSpec$Builder.comment able to be called multiple times for the same entry. (#9056) Maybe that's the issue, no idea. Could just be a startup timing issue.

If starting with no config, game crashes before it is even generated.

I've had this problem on a couple of my mods. I had to move Config registration out of the Forge FMLConstructModEvent into the main function.

**Comment by wendall911** [comment]
I rebuilt locally using the safeRunForDist proxy as a dist executor. I'm not sure if it's what you want for a change, but it doesn't crash.

`    public GlobalGR() {
        Proxy proxy = DistExecutor.safeRunForDist(() -> Proxy::new, () -> Proxy::new);
        proxy.constructMod();
        MinecraftForge.EVENT_BUS.register(WorldEvents.class);
    }

    private class Proxy {
        private void constructMod() {
            ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, GGRConfig.commonSpec);
        }
    }`

**Comment by GoryMoon** [comment]
Haven't been able to replicate this issue on multipe computers running only with this mod.
If you could post the `debug.log` or `latest.log` from a crash it might be helpful in finding the real issue.

**Comment by ChasrielS** [comment]
I also have this crash.
[debug.log](https://github.com/GoryMoon/GlobalGameRules/files/9921740/debug.log)
[latest.log](https://github.com/GoryMoon/GlobalGameRules/files/9921743/latest.log)
[crash-2022-11-02_23.07.02-server.txt](https://github.com/GoryMoon/GlobalGameRules/files/9921744/crash-2022-11-02_23.07.02-server.txt)
Hope you can fix it

**Comment by Orgamorsh** [comment]
I also have this crash. I read that crash report, and it is for the same gory moon in enhanced celestials.

**Comment by Houtblokje** [comment]
I am having the same issue. I have also noticed the config file not generating.

**Comment by GoryMoon** [comment]
@ChasrielS Your files are empty, probably some issue when uploading them.
I would prefer a paste site rather then uploading the file, like:
- https://gist.github.com
- https://paste.ee
- https://pastebin.com

**Comment by ghost** [comment]
I choose to upload the file and submit it for the last time. If it still can't be fixed, forget it!
[crash-2023-01-09_10.30.54-server.txt](https://github.com/GoryMoon/GlobalGameRules/files/10370053/crash-2023-01-09_10.30.54-server.txt)
[latest.log](https://github.com/GoryMoon/GlobalGameRules/files/10370054/latest.log)

**Comment by ghost** [comment]
If you can't reproduce, I'll upload a modpack.
[modpack.zip](https://github.com/GoryMoon/GlobalGameRules/files/10370062/modpack.zip)

**Comment by lynnpye** [comment]
For what it's worth, I have found at least one mod which, when included with this one, triggers the crash consistently:

https://www.curseforge.com/minecraft/mc-mods/better-mob-griefing-control

In CurseForge, if I create a custom modpack with GGR, at Forge 43.2.7, it works. If I include Better Mob Griefing Control along with GGR, GGR crashes. And of course, BMGC is part of a larger modpack I have already been running successfully, so I know it works too.

I suspect it is a load order issue as well, given @wendall911 's workaround.

EDIT: It also appears that a combination of GGR and Twilight Forest (https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest) will crash to desktop upon world creation.

**Comment by Cobyt3** [comment]
I have the same issue, although I noticed it only happens if I set a global Command so that it's running the command upon world creation

**Comment by BlackAures1** [comment]
Are there plans to fix this crash?

**Comment by BlackAures1** [comment]
[crash-2023-05-24_21.56.46-server.txt](https://github.com/GoryMoon/GlobalGameRules/files/11558028/crash-2023-05-24_21.56.46-server.txt)
[crash-2023-05-24_21.48.26-server.txt](https://github.com/GoryMoon/GlobalGameRules/files/11558029/crash-2023-05-24_21.48.26-server.txt)
[debug.log](https://github.com/GoryMoon/GlobalGameRules/files/11558030/debug.log)
[latest.log](https://github.com/GoryMoon/GlobalGameRules/files/11558032/latest.log)
It enters the menu correctly, but crashes when you try to open the old world (new world too)
