### ISSUE TITLE
Can you add more languages?

### ISSUE THREAD

**Issue by axin0452** [GoryMoon/GlobalGameRules#3]
Can you add more language files to the configuration file?

**Comment by GoryMoon** [comment]
What do you mean, add more languages to the `globalgamerules.cfg` file or the in-game config.

If you mean the `.cfg` file that's not going to happen, what language is used isn't known to the config file and needs to match for all setups, i.e. for modpacks.

If you mean the in-game config you can make a copy of the https://github.com/GoryMoon/GlobalGameRules/blob/master/src/main/resources/assets/globalgamerules/lang/en_US.lang and renaming it to the language you want, then translating the file and finally making a pull request. 

Edit:
On looking at it some more I saw that for the tooltips I need to make some changes for those the be translatable.

**Comment by axin0452** [comment]
in `globalgamerules.cfg`, there are lots of comments in English, after I change it to Chinese and restart the server, all these comments will revert back to English

**Comment by GoryMoon** [comment]
Those comments are not meant to be translatable, it's not on my end but on Forges end and like I said above `what language is used isn't known to the config file and needs to match for all setups, i.e. for modpacks.`. Anyone on any system should be able to read them with any game run inbetween.
