### ISSUE TITLE
Crash when generating or loading world

### ISSUE THREAD

**Issue by Wxrlds** [GoryMoon/GlobalGameRules#6]
With the [5.0.1.3](https://www.curseforge.com/minecraft/mc-mods/global-gamerules/files/3212242) update of the mod loading or creating a world results in a crash.
Crash Log: https://gist.github.com/Wxrlds/bd7212e525e4e8aeefc61b2d77d5ccab

**Comment by Wizelf402** [comment]
I'm having the same problem, actually!

**Comment by GoryMoon** [comment]
I know it's been some time, but if you still have the problem try the latest version https://www.curseforge.com/minecraft/mc-mods/global-gamerules/files/3378657
